### ISSUE TITLE
Cannot install (problem with composer on PHP 7.2)

### ISSUE THREAD

**Issue by kylelondonuk** [jolicode/slack-php-api#20] opened 2019-03-25 18:12 UTC
Hi, I tried running your suggested composer commands, but when I open vendor/autoload.php, I get this:

```
[25-Mar-2019 18:10:12 UTC] PHP Fatal error:  Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors
 - Puli Factory is not available
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: .
 - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\ResponseFactory, Http\Factory\Diactoros\ResponseFactory, Http\Factory\Guzzle\ResponseFactory, Http\Factory\Slim\ResponseFactory.

 in /home/mgtckfyeswfr/apis/slack/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41
Stack trace:
#0 /home/mgtckfyeswfr/apis/slack/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\Exception\DiscoveryFailedException::create(Array)
#1 /home/mgtckfyeswfr/apis/slack/vendor/php-http/discovery/src/Psr17Factory in /home/mgtckfyeswfr/apis/slack/vendor/php-http/discovery/src/ClassDiscovery.php on line 210

```

I am running PHP 7.2. I looked at this link: http://docs.php-http.org/en/latest/discovery.html#common-errors and tried installing all the packages it mentions, but when I try the Puli install:

```
composer require puli/composer-plugin
```

i get this:

```
[InvalidArgumentException]                    
  Could not find package puli/composer-plugin.  
                                                
  Did you mean this?                            
      puli/composer-plugin
```

it looks like a full stop is somehow being added to the end of the word plugin?

Can you help?

**Comment by pyrech** [comment] 2019-03-25 18:21
Hum, it looks like php-http fail to find a suitable factory for http messages. I'm pretty sure Puli is not the best option.
Did you run the command `compose composer require php-http/curl-client guzzlehttp/psr7`? What was the output? It should have install the factories from Guzzle.

**Comment by kylelondonuk** [comment] 2019-03-25 18:27
And then I run this with my token, which is where the error comes:
```
$client = JoliCode\Slack\ClientFactory::create($yourToken);
```

**Comment by kylelondonuk** [comment] 2019-03-25 18:32
And if it helps, here's the composer.json  file:
```
"require": {
        "php-http/curl-client": "^2.0",
        "guzzlehttp/psr7": "^1.5",
        "jolicode/slack-php-api": "^1.1"
    }
```

**Comment by kylelondonuk** [comment] 2019-03-25 18:40
Ah, i did
```
composer require zendframework/zend-diactoros
```

and that worked - was the problem just that guzzle wasn't installing the discovery factories for me?

**Comment by pyrech** [comment] 2019-03-26 09:36
This behavior is quite strange because, as far as I know, `zendframework/zend-diactoros` & `guzzlehttp/psr7` are equivalent libraries providing both PSR-7 implementations. They should work similarly. I do not really understand why guzzle's one is not detected correctly by the [CommonClassesStrategy discovery](https://github.com/php-http/discovery/blob/master/src/Strategy/CommonClassesStrategy.php#L46-L63) :confused: 

I would say if Zend Diactoros works for you, just go ahead with it and remove `guzzlehttp/psr7` :wink:

**Comment by vmunich** [comment] 2019-03-29 19:15
I was having this when using `guzzlehttp/psr7`:
```
Http/Discovery/Exception/ClassInstantiationFailedException with message 'Unexpected exception when instantiating class.'
```

However, it works as expected when I install `zendframework/zend-diactoros` instead.

**Comment by damienalexandre** [comment] 2019-04-23 12:38
Confirmed, the installation steps are broken. I'm going to take a deeper look at it.

**Comment by pawelkmpt** [comment] 2019-04-23 12:52
It also fails for me. I tried to install `puli/composer-plugin` as suggested in http://docs.php-http.org/en/latest/discovery.html#puli-factory-is-not-available but failed as well.

```
composer require puli/composer-plugin
                                                                                                                                                                                     
  [InvalidArgumentException]                                                                                                                                                         
  Could not find a version of package puli/composer-plugin matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability. 
```

Defining version of that package also fails as one of its dependencies doesn't meet minimum stability condition. Basically chain reaction of errors.

**Comment by damienalexandre** [comment] 2019-04-23 13:51
As a quick fix you can just force this package to version 1.x, the new 2.x version seams to be the problem:

```
"php-http/curl-client": "^1.0",
```

**Comment by damienalexandre** [comment] 2019-04-23 13:59
Just updated the documentation. Please do not use curl-client 2.0, I have no idea why it does not found the client.

`composer require php-http/curl-client:"^1.7" guzzlehttp/psr7`

**Comment by pawelkmpt** [comment] 2019-04-24 15:04
> `composer require php-http/curl-client:"^1.7" guzzlehttp/psr7`

it works! thanks!

**Comment by pyrech** [comment] 2019-10-03 11:44
Closing as this issue is fixed now. Please feel free to open a new ticket if someone face again a similar error :slightly_smiling_face:

**Closed by pyrech** 2019-10-03 11:44 UTC
